Add bookings
IP71/java-shareit pull request #4
Opened 2023-10-23 12:56 UTC by IP71

2023-10-24 17:54 UTC, kriwsha requested changes

2023-10-24 17:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Строки - не самый надежный инструмент - одна небольшая ошибка, и это уже не работает.  Я бы рекомендовал это исправить на перечисления. Там же (в перечислениях) можно проводить валидацию входящей строки.

2023-10-24 17:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return result.stream().map(BookingMapper::toBookingDto).collect(Collectors.toList());
Стримы выглядят лучше, когда разбиты по операциям на строки

2023-10-24 17:54 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +create(Item, long) создает новую вещь
Вот это писание все таки лучше на методы перенести. Не все будут искать, где описан метод - будут просто смотреть, что ничего нет над методом, а значит нет описания. А еще есть автоматические проверки, которые не пропустят такое описание. 
Эта рекомендация относится также и к другим интерфейсам.

2023-10-24 22:27 UTC, IP71 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Я понимаю, но это нельзя сделать так, чтобы выполнялись все тесты. Т.к. если в контроллер передается неподходящее значение state, в случае с перечислениями возвращается дефолтное сообщение об ошибке, в случае со строками можно вернуть свое.

2023-10-25 14:14 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Не совсем понимаю, что такое дефолтное сообщение об ошибке. Если вы говорите об исключении, возникающем при использовании метода valueOf(), то вы же можете регулировать, что делать с этим исключением. Н-р, вы же умеете их отлавливать.

2023-10-25 14:15 UTC, kriwsha requested changes

2023-10-25 14:15 UTC, kriwsha commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +create(BookingDto, Long) создает новое бронирование
Вы решили так оставить? Или пропустили другие интерфейсы?

2023-10-25 19:03 UTC, IP71 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Да, это то, что имелось ввиду. При передаче в адресе ...?state=x где x не является поддерживаемой операцией, нужно вернуть определенную строку-сообщение об ошибке, содержащее этот x. Можно использовать костыль и обрезать сообщение в исключении при методе valueOf(), чтобы оно содержало только этот x (что я и сделал). Или вы имели ввиду принимать в контроллер все равно строку, а потом переделывать в перечисление в enum классе?
В любом случае это полезное замечание, спасибо

2023-10-26 21:28 UTC, merged